ARG CLI_IMAGE
FROM ${CLI_IMAGE:-builder} as builder

FROM amazeeio/nginx
COPY lagoon/nginx.conf /etc/nginx/conf.d/app.conf
COPY lagoon/redirects-map.conf /etc/nginx/redirects-map.conf

COPY --from=builder /app /app

ENV WEBROOT=web