FROM amazeeio/php:7.1-cli
COPY composer.json composer.lock /app/

# Install wp-cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && chmod +x /usr/local/bin/wp

# Add function to .bashrc to run wp-cli with --allow-root
RUN echo 'wp() { /usr/local/bin/wp "$@" --allow-root; }' >>  ~/.bashrc

RUN composer install --prefer-dist

COPY . /app

ENV WEBROOT=web
ENV PAGER=less
